version: 2
project_name: noxdir

before:
  hooks:
    - go mod tidy

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

nfpms:
  - package_name: noxdir
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: "https://github.com/crumbyte/noxdir"
    description: "Terminal utility for visualizing file system usage."
    maintainer: crumbyte <oleksiivodotyiets@gmail.com>
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    contents:
      # man page
      - src: ./man/noxdir.1
        dst: /usr/share/man/man1/noxdir.1
      # completions
      - src: ./completion/noxdir.bash
        dst: /usr/share/bash-completion/completions/noxdir
      - src: ./completion/noxdir.zsh
        dst: /usr/share/zsh/site-functions/_noxdir
      - src: ./completion/noxdir.fish
        dst: /usr/share/fish/vendor_completions.d/noxdir.fish
      # docs
      - src: ./LICENSE
        dst: /usr/share/doc/noxdir/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/noxdir/README.md

builds:
  - id: noxdir
    binary: noxdir
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    overrides:
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=1
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1

archives:
  - formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}-
      {{- .Tag -}}-
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - LICENSE*
      - README*
      - man/*
      - completion/*

homebrew_casks:
  - name: noxdir
    binary: noxdir
    manpages:
      - man/noxdir.1
    completions:
      bash: completion/noxdir.bash
      zsh: completion/noxdir.zsh
      fish: completion/noxdir.fish
    directory: Casks
    homepage: "https://github.com/crumbyte/noxdir"
    description: "Terminal utility for visualizing file system usage."
    skip_upload: auto
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxdir"]
          end
    repository:
      owner: crumbyte
      name: homebrew-noxdir
      branch: main
      token: "{{ .Env.GH_PAT }}"
  - name: noxdir-nightly
    binary: noxdir
    manpages:
      - man/noxdir.1
    completions:
      bash: completion/noxdir.bash
      zsh: completion/noxdir.zsh
      fish: completion/noxdir.fish
    directory: Casks
    homepage: "https://github.com/crumbyte/noxdir"
    description: "Nightly build of the terminal utility for visualizing file system usage."
    skip_upload: '{{ not (contains .Tag "nightly") }}'
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxdir"]
          end
    repository:
      owner: crumbyte
      name: homebrew-noxdir
      branch: main
      token: "{{ .Env.GH_PAT }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "README.MD"
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  github:
    owner: crumbyte
    name: noxdir
  name_template: '{{.ProjectName}}-{{ if eq .Tag "nightly" }}nightly{{ else }}v{{.Version}}{{ end }}'
